spring:
  datasource:
    url: jdbc:mysql://192.168.1.99:3306/testingsystem?serverTimezone=UTC
    username: root
    password: 091094
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
eureka:
  instance:
    prefer-ip-address: true
    hostname: 192.168.1.99
  client:
    service-url:
      defaultZone: http://192.168.1.99:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.1.99:9411/api/v2/spans